<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_parotid_cells [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (parotid_cells)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT parotid_cells (cell, lumen)>
	<!ATTLIST parotid_cells id NMTOKEN #REQUIRED>
	<!ATTLIST parotid_cells expanded NMTOKEN #REQUIRED>
	<!ELEMENT cell (area_list)>
	<!ATTLIST cell id NMTOKEN #REQUIRED>
	<!ATTLIST cell expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT lumen (treeline)>
	<!ATTLIST lumen id NMTOKEN #REQUIRED>
	<!ATTLIST lumen expanded NMTOKEN #REQUIRED>
	<!ELEMENT treeline EMPTY>
	<!ATTLIST treeline id NMTOKEN #REQUIRED>
	<!ATTLIST treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST treeline expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="cell_mesh.xml"
		unuid="1470358891671.2094521328.1151407996"
		mipmaps_folder="trakem2.1470358891671.2094521328.1151407996/trakem2.mipmaps/"
		storage_folder=""
		mipmaps_format="4"
		image_resizing_mode="Area downsampling"
	>
		<parotid_cells id="104" expanded="true">
			<cell id="105" expanded="true">
				<area_list id="107" oid="106"/>
			</cell>
			<cell id="108" expanded="true">
				<area_list id="110" oid="109"/>
			</cell>
		</parotid_cells>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="1024.0"
		layer_height="1024.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="0.069"
			pixelHeight="0.069"
			pixelDepth="1.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="µm"
		/>
		<t2_area_list
			oid="106"
			width="220.0"
			height="221.0"
			transform="matrix(1.0,0.0,0.0,1.0,378.0,198.0)"
			title="cell01"
			links="59,62,65,68,71,74,77,80,83,86,89,92,95,98"
			layer_set_id="3"
			fill_paint="true"
			style="stroke:none;fill-opacity:0.39;fill:#ffa05d;"
		>
			<t2_area layer_id="69">
				<t2_path d="M 100 37 L 100 38 L 96 38 L 96 39 L 94 39 L 94 40 L 93 40 L 93 41 L 92 41 L 92 42 L 91 42 L 91 43 L 90 43 L 90 44 L 89 44 L 89 45 L 88 45 L 88 46 L 87 46 L 87 47 L 86 47 L 86 48 L 85 48 L 85 49 L 84 49 L 84 50 L 80 50 L 80 51 L 78 51 L 78 52 L 77 52 L 77 53 L 76 53 L 76 54 L 74 54 L 74 55 L 72 55 L 72 56 L 71 56 L 71 57 L 69 57 L 69 58 L 68 58 L 68 59 L 64 59 L 64 60 L 62 60 L 62 61 L 61 61 L 61 62 L 59 62 L 59 63 L 57 63 L 57 64 L 56 64 L 56 65 L 55 65 L 55 66 L 54 66 L 54 67 L 52 67 L 52 68 L 51 68 L 51 69 L 50 69 L 50 70 L 49 70 L 49 71 L 48 71 L 48 72 L 47 72 L 47 74 L 46 74 L 46 75 L 45 75 L 45 76 L 44 76 L 44 77 L 43 77 L 43 78 L 42 78 L 42 79 L 41 79 L 41 80 L 40 80 L 40 81 L 39 81 L 39 82 L 38 82 L 38 84 L 37 84 L 37 85 L 36 85 L 36 86 L 35 86 L 35 87 L 34 87 L 34 88 L 33 88 L 33 89 L 32 89 L 32 90 L 31 90 L 31 92 L 30 92 L 30 95 L 29 95 L 29 97 L 28 97 L 28 99 L 27 99 L 27 101 L 26 101 L 26 104 L 25 104 L 25 108 L 24 108 L 24 110 L 23 110 L 23 112 L 22 112 L 22 117 L 23 117 L 23 121 L 24 121 L 24 123 L 25 123 L 25 127 L 26 127 L 26 129 L 27 129 L 27 134 L 27 135 L 28 135 L 28 140 L 29 140 L 29 143 L 30 143 L 30 148 L 31 148 L 31 153 L 31 154 L 32 154 L 32 156 L 33 156 L 33 158 L 34 158 L 34 160 L 35 160 L 35 163 L 36 163 L 36 166 L 37 166 L 37 168 L 38 168 L 38 170 L 39 170 L 39 172 L 40 172 L 40 174 L 41 174 L 41 178 L 42 178 L 42 180 L 43 180 L 43 182 L 44 182 L 44 184 L 45 184 L 45 185 L 46 185 L 46 186 L 47 186 L 47 187 L 48 187 L 48 188 L 49 188 L 49 189 L 50 189 L 50 190 L 51 190 L 51 191 L 52 191 L 52 192 L 54 192 L 54 194 L 55 194 L 55 195 L 56 195 L 56 196 L 57 196 L 57 197 L 58 197 L 58 198 L 59 198 L 59 199 L 60 199 L 60 200 L 61 200 L 61 201 L 62 201 L 62 202 L 64 202 L 64 203 L 68 203 L 68 204 L 71 204 L 71 205 L 76 205 L 76 206 L 79 206 L 79 207 L 82 207 L 82 208 L 86 208 L 86 209 L 94 209 L 94 210 L 112 210 L 112 209 L 114 209 L 114 208 L 117 208 L 117 207 L 119 207 L 119 206 L 122 206 L 122 205 L 124 205 L 124 204 L 125 204 L 125 203 L 126 203 L 126 202 L 127 202 L 127 201 L 128 201 L 128 200 L 129 200 L 129 199 L 130 199 L 130 197 L 131 197 L 131 195 L 132 195 L 132 194 L 132 193 L 134 193 L 134 192 L 136 192 L 136 191 L 137 191 L 137 190 L 138 190 L 138 189 L 139 189 L 139 188 L 140 188 L 140 187 L 141 187 L 141 186 L 143 186 L 143 185 L 144 185 L 144 184 L 145 184 L 145 183 L 147 183 L 147 182 L 149 182 L 149 181 L 151 181 L 151 180 L 154 180 L 154 179 L 159 179 L 159 178 L 162 178 L 162 177 L 166 177 L 166 176 L 168 176 L 168 175 L 169 175 L 169 174 L 170 174 L 170 173 L 171 173 L 171 172 L 172 172 L 172 171 L 173 171 L 173 169 L 174 169 L 174 168 L 174 167 L 174 166 L 174 164 L 175 164 L 175 163 L 175 161 L 175 159 L 175 158 L 175 153 L 174 153 L 174 151 L 173 151 L 173 149 L 172 149 L 172 148 L 171 148 L 171 146 L 170 146 L 170 144 L 169 144 L 169 142 L 168 142 L 168 140 L 167 140 L 167 138 L 166 138 L 166 137 L 165 137 L 165 134 L 164 134 L 164 132 L 163 132 L 163 130 L 162 130 L 162 129 L 162 124 L 161 124 L 161 122 L 160 122 L 160 121 L 159 121 L 159 117 L 158 117 L 158 115 L 157 115 L 157 113 L 156 113 L 156 111 L 155 111 L 155 110 L 154 110 L 154 108 L 153 108 L 153 107 L 152 107 L 152 106 L 151 106 L 151 105 L 150 105 L 150 104 L 148 104 L 148 103 L 147 103 L 147 102 L 146 102 L 146 101 L 144 101 L 144 100 L 143 100 L 143 99 L 142 99 L 142 98 L 141 98 L 141 97 L 140 97 L 140 96 L 139 96 L 139 95 L 138 95 L 138 92 L 137 92 L 137 90 L 137 89 L 137 84 L 136 84 L 136 82 L 135 82 L 135 79 L 134 79 L 134 77 L 134 74 L 134 73 L 134 68 L 133 68 L 133 66 L 132 66 L 132 65 L 131 65 L 131 63 L 130 63 L 130 61 L 129 61 L 129 59 L 128 59 L 128 58 L 127 58 L 127 57 L 126 57 L 126 56 L 125 56 L 125 55 L 123 55 L 123 54 L 121 54 L 121 52 L 120 52 L 120 50 L 119 50 L 119 49 L 119 44 L 118 44 L 118 42 L 117 42 L 117 41 L 116 41 L 116 40 L 114 40 L 114 39 L 113 39 L 113 38 L 111 38 L 111 37 z" />
			</t2_area>
			<t2_area layer_id="96">
				<t2_path d="M 90 37 L 90 38 L 87 38 L 87 39 L 85 39 L 85 40 L 83 40 L 83 41 L 82 41 L 82 42 L 81 42 L 81 43 L 80 43 L 80 44 L 79 44 L 79 45 L 78 45 L 78 47 L 77 47 L 77 49 L 76 49 L 76 51 L 75 51 L 75 52 L 74 52 L 74 53 L 72 53 L 72 54 L 69 54 L 69 55 L 67 55 L 67 56 L 66 56 L 66 57 L 65 57 L 65 59 L 63 59 L 63 60 L 62 60 L 62 61 L 61 61 L 61 62 L 59 62 L 59 63 L 57 63 L 57 64 L 56 64 L 56 65 L 55 65 L 55 67 L 54 67 L 54 68 L 52 68 L 52 69 L 51 69 L 51 70 L 50 70 L 50 72 L 49 72 L 49 74 L 48 74 L 48 75 L 47 75 L 47 77 L 46 77 L 46 82 L 46 85 L 46 88 L 46 91 L 46 94 L 46 98 L 47 98 L 47 100 L 48 100 L 48 101 L 49 101 L 49 103 L 50 103 L 50 104 L 51 104 L 51 105 L 52 105 L 52 107 L 53 107 L 53 108 L 54 108 L 54 109 L 55 109 L 55 111 L 56 111 L 56 112 L 57 112 L 57 113 L 59 113 L 59 114 L 60 114 L 60 115 L 61 115 L 61 116 L 62 116 L 62 117 L 63 117 L 63 118 L 64 118 L 64 119 L 66 119 L 66 120 L 67 120 L 67 121 L 69 121 L 69 122 L 71 122 L 71 123 L 73 123 L 73 124 L 76 124 L 76 125 L 77 125 L 77 126 L 79 126 L 79 127 L 85 127 L 85 128 L 89 128 L 89 129 L 99 129 L 99 128 L 101 128 L 101 127 L 102 127 L 102 126 L 103 126 L 103 124 L 104 124 L 104 123 L 105 123 L 105 122 L 106 122 L 106 120 L 107 120 L 107 119 L 107 118 L 107 117 L 107 115 L 108 115 L 108 114 L 108 112 L 108 110 L 108 108 L 109 108 L 109 107 L 109 106 L 110 106 L 110 105 L 111 105 L 111 104 L 112 104 L 112 103 L 113 103 L 113 101 L 114 101 L 114 100 L 114 99 L 115 99 L 115 98 L 116 98 L 116 96 L 117 96 L 117 95 L 117 93 L 118 93 L 118 92 L 119 92 L 119 90 L 120 90 L 120 89 L 120 86 L 120 83 L 120 81 L 121 81 L 121 80 L 121 79 L 121 78 L 121 75 L 121 74 L 121 69 L 120 69 L 120 67 L 119 67 L 119 66 L 118 66 L 118 63 L 117 63 L 117 61 L 116 61 L 116 57 L 115 57 L 115 55 L 114 55 L 114 53 L 113 53 L 113 51 L 112 51 L 112 49 L 111 49 L 111 44 L 110 44 L 110 42 L 109 42 L 109 41 L 108 41 L 108 40 L 107 40 L 107 39 L 106 39 L 106 38 L 104 38 L 104 37 z" />
			</t2_area>
			<t2_area layer_id="66">
				<t2_path d="M 76 57 L 76 58 L 74 58 L 74 59 L 73 59 L 73 60 L 71 60 L 71 61 L 70 61 L 70 62 L 68 62 L 68 63 L 66 63 L 66 64 L 65 64 L 65 65 L 64 65 L 64 66 L 63 66 L 63 67 L 62 67 L 62 68 L 60 68 L 60 69 L 59 69 L 59 70 L 58 70 L 58 71 L 57 71 L 57 72 L 56 72 L 56 73 L 55 73 L 55 74 L 54 74 L 54 75 L 53 75 L 53 76 L 52 76 L 52 77 L 51 77 L 51 78 L 50 78 L 50 80 L 48 80 L 48 81 L 47 81 L 47 82 L 46 82 L 46 84 L 45 84 L 45 85 L 44 85 L 44 86 L 43 86 L 43 87 L 42 87 L 42 88 L 41 88 L 41 90 L 40 90 L 40 92 L 39 92 L 39 94 L 38 94 L 38 96 L 37 96 L 37 97 L 36 97 L 36 98 L 35 98 L 35 100 L 34 100 L 34 104 L 33 104 L 33 105 L 32 105 L 32 106 L 31 106 L 31 107 L 30 107 L 30 109 L 29 109 L 29 111 L 28 111 L 28 116 L 28 118 L 28 122 L 28 125 L 29 125 L 29 130 L 29 133 L 30 133 L 30 137 L 31 137 L 31 140 L 32 140 L 32 142 L 33 142 L 33 145 L 34 145 L 34 147 L 35 147 L 35 148 L 36 148 L 36 150 L 37 150 L 37 152 L 38 152 L 38 153 L 39 153 L 39 157 L 40 157 L 40 159 L 41 159 L 41 161 L 42 161 L 42 162 L 43 162 L 43 163 L 44 163 L 44 165 L 45 165 L 45 167 L 46 167 L 46 169 L 47 169 L 47 171 L 48 171 L 48 174 L 49 174 L 49 176 L 50 176 L 50 180 L 50 183 L 50 186 L 49 186 L 49 191 L 50 191 L 50 194 L 51 194 L 51 197 L 52 197 L 52 199 L 53 199 L 53 201 L 54 201 L 54 202 L 55 202 L 55 203 L 57 203 L 57 204 L 59 204 L 59 205 L 67 205 L 67 206 L 76 206 L 76 207 L 78 207 L 78 208 L 84 208 L 84 207 L 86 207 L 86 206 L 95 206 L 95 205 L 103 205 L 103 204 L 105 204 L 105 203 L 112 203 L 112 202 L 116 202 L 116 201 L 118 201 L 118 200 L 124 200 L 124 199 L 126 199 L 126 198 L 129 198 L 129 197 L 132 197 L 132 196 L 134 196 L 134 195 L 136 195 L 136 194 L 138 194 L 138 193 L 139 193 L 139 192 L 141 192 L 141 191 L 142 191 L 142 190 L 144 190 L 144 189 L 146 189 L 146 188 L 147 188 L 147 187 L 149 187 L 149 186 L 150 186 L 150 185 L 151 185 L 151 184 L 152 184 L 152 183 L 153 183 L 153 182 L 155 182 L 155 181 L 156 181 L 156 180 L 157 180 L 157 179 L 158 179 L 158 178 L 159 178 L 159 176 L 160 176 L 160 175 L 160 173 L 160 172 L 160 171 L 161 171 L 161 169 L 162 169 L 162 168 L 162 164 L 162 159 L 161 159 L 161 157 L 160 157 L 160 156 L 159 156 L 159 154 L 158 154 L 158 152 L 157 152 L 157 150 L 156 150 L 156 149 L 155 149 L 155 148 L 154 148 L 154 147 L 153 147 L 153 146 L 152 146 L 152 145 L 151 145 L 151 144 L 150 144 L 150 143 L 149 143 L 149 140 L 148 140 L 148 138 L 147 138 L 147 137 L 146 137 L 146 136 L 145 136 L 145 135 L 143 135 L 143 134 L 141 134 L 141 133 L 140 133 L 140 132 L 138 132 L 138 131 L 135 131 L 135 130 L 133 130 L 133 129 L 130 129 L 130 128 L 129 128 L 129 127 L 128 127 L 128 126 L 127 126 L 127 123 L 126 123 L 126 122 L 126 117 L 125 117 L 125 115 L 124 115 L 124 113 L 123 113 L 123 111 L 122 111 L 122 110 L 121 110 L 121 107 L 120 107 L 120 105 L 119 105 L 119 104 L 118 104 L 118 103 L 117 103 L 117 102 L 116 102 L 116 101 L 115 101 L 115 100 L 114 100 L 114 98 L 113 98 L 113 94 L 112 94 L 112 92 L 111 92 L 111 91 L 110 91 L 110 90 L 109 90 L 109 89 L 108 89 L 108 88 L 106 88 L 106 87 L 104 87 L 104 86 L 103 86 L 103 85 L 101 85 L 101 84 L 100 84 L 100 83 L 98 83 L 98 82 L 97 82 L 97 79 L 96 79 L 96 77 L 95 77 L 95 75 L 94 75 L 94 74 L 93 74 L 93 73 L 91 73 L 91 72 L 90 72 L 90 70 L 89 70 L 89 66 L 88 66 L 88 64 L 87 64 L 87 62 L 86 62 L 86 61 L 85 61 L 85 60 L 84 60 L 84 59 L 83 59 L 83 58 L 81 58 L 81 57 z" />
			</t2_area>
			<t2_area layer_id="78">
				<t2_path d="M 125 9 L 125 10 L 124 10 L 124 11 L 123 11 L 123 12 L 121 12 L 121 13 L 118 13 L 118 14 L 116 14 L 116 15 L 111 15 L 111 16 L 107 16 L 107 17 L 105 17 L 105 18 L 91 18 L 91 19 L 89 19 L 89 20 L 83 20 L 83 21 L 78 21 L 78 22 L 77 22 L 77 23 L 76 23 L 76 24 L 75 24 L 75 25 L 74 25 L 74 26 L 73 26 L 73 27 L 72 27 L 72 28 L 69 28 L 69 29 L 68 29 L 68 30 L 67 30 L 67 31 L 66 31 L 66 32 L 65 32 L 65 33 L 64 33 L 64 34 L 63 34 L 63 35 L 62 35 L 62 36 L 61 36 L 61 37 L 60 37 L 60 39 L 59 39 L 59 40 L 58 40 L 58 41 L 57 41 L 57 43 L 56 43 L 56 44 L 55 44 L 55 45 L 53 45 L 53 46 L 51 46 L 51 47 L 50 47 L 50 48 L 49 48 L 49 51 L 48 51 L 48 52 L 46 52 L 46 54 L 44 54 L 44 55 L 41 55 L 41 56 L 39 56 L 39 57 L 38 57 L 38 58 L 37 58 L 37 59 L 36 59 L 36 60 L 35 60 L 35 61 L 34 61 L 34 62 L 33 62 L 33 65 L 32 65 L 32 66 L 31 66 L 31 69 L 30 69 L 30 70 L 29 70 L 29 71 L 28 71 L 28 72 L 27 72 L 27 73 L 26 73 L 26 74 L 25 74 L 25 75 L 21 75 L 21 76 L 19 76 L 19 77 L 18 77 L 18 78 L 17 78 L 17 79 L 16 79 L 16 80 L 15 80 L 15 82 L 14 82 L 14 84 L 13 84 L 13 86 L 12 86 L 12 88 L 11 88 L 11 90 L 10 90 L 10 92 L 9 92 L 9 95 L 8 95 L 8 96 L 7 96 L 7 97 L 6 97 L 6 98 L 5 98 L 5 103 L 5 105 L 6 105 L 6 107 L 7 107 L 7 112 L 8 112 L 8 114 L 10 114 L 10 116 L 13 116 L 13 117 L 14 117 L 14 118 L 14 120 L 12 120 L 12 122 L 11 122 L 11 128 L 11 129 L 12 129 L 12 131 L 11 131 L 11 136 L 11 141 L 12 141 L 12 144 L 13 144 L 13 147 L 14 147 L 14 149 L 15 149 L 15 152 L 16 152 L 16 155 L 17 155 L 17 157 L 18 157 L 18 158 L 19 158 L 19 159 L 20 159 L 20 160 L 21 160 L 21 162 L 22 162 L 22 164 L 23 164 L 23 165 L 24 165 L 24 166 L 25 166 L 25 167 L 26 167 L 26 169 L 27 169 L 27 170 L 28 170 L 28 171 L 30 171 L 30 173 L 31 173 L 31 174 L 32 174 L 32 176 L 33 176 L 33 177 L 34 177 L 34 178 L 35 178 L 35 179 L 36 179 L 36 180 L 37 180 L 37 181 L 38 181 L 38 182 L 39 182 L 39 183 L 40 183 L 40 184 L 41 184 L 41 185 L 42 185 L 42 186 L 45 186 L 45 187 L 46 187 L 46 189 L 47 189 L 47 191 L 48 191 L 48 193 L 50 193 L 50 195 L 52 195 L 52 197 L 54 197 L 54 198 L 55 198 L 55 199 L 56 199 L 56 200 L 57 200 L 57 201 L 58 201 L 58 202 L 59 202 L 59 203 L 60 203 L 60 204 L 61 204 L 61 205 L 62 205 L 62 206 L 63 206 L 63 207 L 64 207 L 64 208 L 66 208 L 66 210 L 68 210 L 68 211 L 70 211 L 70 212 L 73 212 L 73 213 L 74 213 L 74 214 L 76 214 L 76 215 L 80 215 L 80 217 L 81 217 L 81 218 L 82 218 L 82 219 L 84 219 L 84 220 L 94 220 L 94 221 L 114 221 L 114 220 L 117 220 L 117 219 L 119 219 L 119 218 L 122 218 L 122 217 L 124 217 L 124 216 L 127 216 L 127 215 L 129 215 L 129 214 L 131 214 L 131 213 L 132 213 L 132 212 L 133 212 L 133 211 L 135 211 L 135 210 L 136 210 L 136 209 L 138 209 L 138 208 L 139 208 L 139 207 L 140 207 L 140 206 L 141 206 L 141 205 L 142 205 L 142 204 L 143 204 L 143 203 L 144 203 L 144 202 L 145 202 L 145 201 L 146 201 L 146 200 L 147 200 L 147 199 L 148 199 L 148 198 L 149 198 L 149 197 L 151 197 L 151 196 L 152 196 L 152 195 L 153 195 L 153 194 L 154 194 L 154 193 L 155 193 L 155 192 L 157 192 L 157 191 L 158 191 L 158 190 L 159 190 L 159 189 L 160 189 L 160 188 L 161 188 L 161 187 L 162 187 L 162 186 L 164 186 L 164 185 L 165 185 L 165 184 L 167 184 L 167 183 L 168 183 L 168 182 L 169 182 L 169 181 L 170 181 L 170 179 L 171 179 L 171 177 L 172 177 L 172 175 L 173 175 L 173 173 L 174 173 L 174 172 L 175 172 L 175 171 L 176 171 L 176 170 L 177 170 L 177 169 L 178 169 L 178 168 L 179 168 L 179 166 L 180 166 L 180 165 L 181 165 L 181 164 L 182 164 L 182 163 L 183 163 L 183 162 L 184 162 L 184 160 L 185 160 L 185 159 L 186 159 L 186 158 L 187 158 L 187 157 L 188 157 L 188 156 L 190 156 L 190 155 L 191 155 L 191 153 L 192 153 L 192 151 L 193 151 L 193 150 L 194 150 L 194 149 L 195 149 L 195 148 L 196 148 L 196 147 L 197 147 L 197 145 L 198 145 L 198 144 L 198 142 L 198 141 L 199 141 L 199 140 L 200 140 L 200 139 L 201 139 L 201 137 L 202 137 L 202 135 L 203 135 L 203 132 L 204 132 L 204 131 L 205 131 L 205 130 L 206 130 L 206 128 L 207 128 L 207 127 L 207 122 L 208 122 L 208 121 L 209 121 L 209 119 L 210 119 L 210 115 L 210 110 L 211 110 L 211 106 L 212 106 L 212 104 L 212 102 L 214 102 L 214 100 L 215 100 L 215 99 L 216 99 L 216 97 L 217 97 L 217 96 L 217 91 L 218 91 L 218 87 L 217 87 L 217 84 L 217 81 L 217 77 L 217 73 L 216 73 L 216 69 L 216 66 L 215 66 L 215 65 L 214 65 L 214 63 L 213 63 L 213 62 L 212 62 L 212 60 L 211 60 L 211 58 L 210 58 L 210 57 L 208 57 L 208 56 L 207 56 L 207 55 L 206 55 L 206 54 L 204 54 L 204 53 L 202 53 L 202 52 L 201 52 L 201 51 L 200 51 L 200 50 L 199 50 L 199 48 L 198 48 L 198 45 L 197 45 L 197 43 L 196 43 L 196 42 L 195 42 L 195 41 L 194 41 L 194 39 L 193 39 L 193 37 L 192 37 L 192 34 L 191 34 L 191 33 L 190 33 L 190 32 L 189 32 L 189 31 L 188 31 L 188 30 L 187 30 L 187 29 L 186 29 L 186 28 L 185 28 L 185 27 L 180 27 L 180 26 L 177 26 L 177 25 L 176 25 L 176 24 L 175 24 L 175 23 L 172 23 L 172 20 L 171 20 L 171 19 L 170 19 L 170 18 L 169 18 L 169 17 L 168 17 L 168 16 L 167 16 L 167 15 L 166 15 L 166 14 L 164 14 L 164 13 L 160 13 L 160 12 L 159 12 L 159 11 L 147 11 L 147 10 L 144 10 L 144 9 z" />
			</t2_area>
			<t2_area layer_id="72">